greet_msg = '''שלום, אני קניבוט, בוט הקניות.🤖
אני עוזר לנהל רשימות קניות משותפות בין כמה משתתפים 📝.
מוצרים שיישלחו אלי ממך יופיעו לכל מי שמשתתף ברשימה שלך, וברגע שייקנו אותם אני אעדכן אותך.
כמה פקודות לשימוש בי:
✳️"רשום"- להוספת פריטים לרשימה
✳️"שלח"- לשליחת הרשימה המלאה
✳️"קניתי"- לאיפוס הרשימה
✳️"בטל"- להסרת פריטים מהרשימה'''
help_cmd = 'עזרה'
help_msg = 'אהלן, אני קניבוט.\n פקודות:\n"עזרה": לקבלת הודעה זו\n"שלח": לשליחת הרשימה\n "תרשום": להוספת מוצרים לרשימה'
send_cmd = 'שלח'
send_msg = 'הנה הרשימה:\n'
write_cmd = 'רשום'
instead_cmd = 'במקום'
write_msg = 'אני רושם 📝. בסיום הרשימה נא לשלוח "זהו"'
remove_msg = 'אני מוחק. בסיום הרשימה נא לשלוח "זהו"'
finish_cmd = 'זהו'
finish_write_msg = 'אחלה, רשמתי את הפריטים שביקשת'
failed_msg = 'אופס חלה אצלי תקלה'
bought_cmd = 'קניתי'
bought_msg = 'סגור, איפסתי את הרשימה'
remove_cmd = 'בטל'
finish_remove_msg = 'הסרתי את הפריטים'
debug_cmd = 'דבג'
list_cmd = 'רשימה'
new_cmd = 'חדשה'
already_exists_err = 'כבר יש רשימה בשם "%s"...'
not_exists_err = 'אין לך רשימה בשם "%s"...'
list_msg = 'מעכשיו אני עורך את הרשימה "%s"'
new_msg = 'יצרתי רשימה חדשה בשם "%s"'
new_list_msg = 'יצרתי רשימה חדשה בשם "%s" ומעכשיו אני עורך אותה'
no_item_err = 'סליחה, לא הצלחתי להבין למה התכוונת'
no_working_list_err = 'לא פתחת אף רשימה...'
default_working_state_err = 'לא הבנתי מה לעשות עם מה שכתבת...'
empty_list_err = 'הרשימה ריקה...'
mem = 'מ'
vav = 'ו'
existing_item_err = 'חוץ מ%s שכבר יש ברשימה'
non_existing_item_err = 'חוץ מ%s, פריט שלא הופיע ברשימה'
non_existing_items_err = 'חוץ מ%s, פריטים שלא הופיעו ברשימה'
share_msg = 'שיתפתי את הרשימה עם המשתמשים'
set_admins_msg = 'הפכתי את המשתמשים למנהלים'
unrecognized_msg_err = 'סליחה, לא הבנתי את ההודעה שלך. לקבלת עזרה ניתן לשלוח "עזרה"'
exception_err = 'סליחה, חלה תקלה:\n'
not_admin_err = 'סליחה, לא ניתן לבצע את הפעולה ללא הרשאות מנהל. ניתן לבקש הרשאות מאחד המנהלים של הרשימה'
